"""Run configuration for the analyzer.

Mirrors the OPTIONS block at the top of X4SaveGameAnalysis.R.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Config:
    # Directory containing X4 user data (the folder with <player-id>/save/).
    # Searched recursively for save directories, so pointing at the parent works too.
    x4_user_dir: Path = Path("~/.config/EgoSoft/X4").expanduser()

    # X4 installation directory (used by `extract-gamedata` only).
    game_dir: Path = Path("/games/SteamLibrary/steamapps/common/X4 Foundations")

    # Reference CSVs regenerated by `extract-gamedata`; caches also live here.
    data_dir: Path = field(
        default_factory=lambda: Path(__file__).resolve().parents[2] / "data"
    )

    # Dashboard and widget output.
    output_dir: Path = field(default_factory=lambda: Path.cwd() / "output")

    # Analyze this savegame instead of the most recent one.
    savegame_override: Path | None = None

    # Hide undiscovered sectors/ships/stations and resource detail plots.
    spoilers_hide: bool = False

    # Rebuild the per-game sector resource cache (needed after installing DLC).
    cache_force_refresh: bool = False

    # gzip the cache files.
    cache_compress: bool = True

    # Hours of history for the sunbursts and earnings tables.
    history_hours: float = 3.0

    # Hours of history for the map's police/pirate overlays.
    overlay_hours: float = 24.0

    # Open the dashboard in the default browser when done.
    open_browser: bool = True

    def find_savegame(self) -> Path:
        """Return the savegame to analyze (override, or newest by mtime)."""
        if self.savegame_override is not None:
            if not self.savegame_override.exists():
                raise FileNotFoundError(
                    f"savegame override does not exist: {self.savegame_override}"
                )
            return self.savegame_override

        save_dirs = [
            d
            for d in self.x4_user_dir.rglob("save")
            if d.is_dir() and re.search(r"/[0-9]+/save$", d.as_posix())
        ]
        saves = [
            f
            for d in save_dirs
            for f in d.iterdir()
            if re.search(r"\.xml(\.gz)?$", f.name)
        ]
        if not saves:
            raise FileNotFoundError(f"no savegames found under {self.x4_user_dir}")
        if any("temp" in f.name for f in saves):
            raise RuntimeError("Game is saving, try again in a minute.")
        return max(saves, key=lambda f: f.stat().st_mtime)
